[project]
name = 'Blockchain-Based-Specialized-Healthcare-Provider-Credentialing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.education-verification]
path = 'contracts/education-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.peer-review]
path = 'contracts/peer-review.clar'
clarity_version = 2
epoch = 2.5

[contracts.provider-identity]
path = 'contracts/provider-identity.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
